//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FastHenry2.rc
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDR_MAINFRAME                   128
#define IDR_FASTHTYPE                   129
#define IDD_DIALOG_RUN                  130
#define IDC_MULTIPOLE_ORDER             1000
#define IDC_STATIC1                     1001
#define IDC_RESET                       1002
#define IDC_SOLVE_ITERATIONS            1003
#define IDC_STATIC2                     1004
#define IDC_INITIAL_REFINEMENT          1005
#define IDC_STATIC3                     1006
#define IDC_ROM_ORDER                   1007
#define IDC_STATIC4                     1008
#define IDC_SHELLS_RADIUS               1009
#define IDC_STATIC5                     1010
#define IDC_FILENAME_SUFFIX             1011
#define IDC_STATIC6                     1012
#define IDC_MATRIX_SOLUTION_METHOD      1013
#define IDC_STATIC7                     1014
#define IDC_MATRIX_VECTOR_PRODUCT       1015
#define IDC_STATIC8                     1016
#define IDC_PRECONDITIONER              1017
#define IDC_STATIC9                     1018
#define IDC_PARTITIONING_LEVELS         1019
#define IDC_STATIC10                    1020
#define IDC_VISUALIZATION_MODE          1021
#define IDC_STATIC11                    1022
#define IDC_GROUND_PLANE                1023
#define IDC_STATIC12                    1024
#define IDC_COMPUTE_PORTS               1025
#define IDC_STATIC17                    1026
#define IDC_DUMP_MATRICES               1027
#define IDC_STATIC13                    1028
#define IDC_DUMP_FILE_TYPE              1029
#define IDC_STATIC14                    1030
#define IDC_TOLERANCE_RTOL              1031
#define IDC_STATIC15                    1032
#define IDC_TOLERANCE_ATOL              1033
#define IDC_STATIC16                    1034
#define IDC_INPUT_FILE_NAME             1035
#define IDC_STATIC20                    1036
#define IDC_AUTOMATIC_REFINE            1039
#define IDC_DEBUG_INFO                  1040
#define IDC_REGURGITATE                 1041
#define IDC_EXIT_AFTER_ROM              1042
#define IDC_PRINT_RESULTS_ON_SCREEN     1043
#define IDC_BROWSE_INPUT_FILE           1044
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_FASTHENRY_STOP               32774
#define ID_FASTHENRY_RUN                32775
#define ID_EDIT_CLEARALL                32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1045
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
